CREATE TABLE principals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 label VARCHAR(120) NOT NULL,
 is_admin TINYINT NOT NULL DEFAULT 0,
 revoked_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE projects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 description TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE memberships (
 principal_id BIGINT UNSIGNED NOT NULL,
 project_id BIGINT UNSIGNED NOT NULL,
 role VARCHAR(16) NOT NULL,
 PRIMARY KEY(principal_id,project_id),
 FOREIGN KEY(principal_id) REFERENCES principals(id),
 FOREIGN KEY(project_id) REFERENCES projects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE invitations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 principal_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE,
 expires_at DATETIME NOT NULL,
 consumed_at DATETIME NULL,
 revoked_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(principal_id) REFERENCES principals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE access_sessions (
 token_hash CHAR(64) PRIMARY KEY,
 principal_id BIGINT UNSIGNED NOT NULL,
 csrf_token CHAR(64) NOT NULL,
 expires_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(principal_id) REFERENCES principals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE tasks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(240) NOT NULL,
 feature VARCHAR(120) NOT NULL DEFAULT '',
 public_summary TEXT NOT NULL,
 scope TEXT NOT NULL,
 criteria TEXT NOT NULL,
 evidence TEXT NOT NULL,
 assignee VARCHAR(120) NOT NULL DEFAULT '',
 blocked_reason TEXT NOT NULL,
 checklist TEXT NOT NULL,
 status TINYINT NOT NULL DEFAULT 0,
 planned_go_live_on DATE NOT NULL,
 actual_released_at DATETIME NULL,
 version INT NOT NULL DEFAULT 1,
 archived TINYINT NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(project_id,archived,status,id),
 FOREIGN KEY(project_id) REFERENCES projects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE task_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 task_id BIGINT UNSIGNED NOT NULL,
 principal_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(80) NOT NULL,
 payload TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(task_id,id),
 FOREIGN KEY(task_id) REFERENCES tasks(id),
 FOREIGN KEY(principal_id) REFERENCES principals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE rate_limits (
 bucket CHAR(64) PRIMARY KEY,
 attempts INT NOT NULL DEFAULT 0,
 expires_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
