CREATE TABLE meetings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(240) NOT NULL,
 meeting_on DATE NOT NULL,
 participants TEXT NOT NULL,
 content MEDIUMTEXT NOT NULL,
 published TINYINT NOT NULL DEFAULT 0,
 version INT NOT NULL DEFAULT 1,
 archived TINYINT NOT NULL DEFAULT 0,
 created_by BIGINT UNSIGNED NOT NULL,
 updated_by BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(project_id,archived,meeting_on,id),
 FOREIGN KEY(project_id) REFERENCES projects(id),
 FOREIGN KEY(created_by) REFERENCES principals(id),
 FOREIGN KEY(updated_by) REFERENCES principals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE meeting_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 meeting_id BIGINT UNSIGNED NOT NULL,
 principal_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(40) NOT NULL,
 payload MEDIUMTEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(meeting_id,id),
 FOREIGN KEY(meeting_id) REFERENCES meetings(id),
 FOREIGN KEY(principal_id) REFERENCES principals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
