import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from './api';
import type { Meeting, Project, Task } from './types';
import FormattedReport from './FormattedReport';
import { today, dateLabel, localDate } from './ProjectViews';
const template='# สรุปการประชุม\n\n## ประเด็นที่หารือ\n- \n\n## ข้อตกลง / มติ\n- \n\n## งานที่ต้องติดตาม\n| งาน | ผู้รับผิดชอบ | กำหนดส่ง |\n| --- | --- | --- |\n|  |  |  |\n\n## ประเด็นค้าง\n- ';
export default function MeetingCalendar({projects,tasks,projectId,onProject,onTask}:{projects:Project[];tasks:Task[];projectId:number|null;onProject:(id:number)=>void;onTask:(t:Task)=>void}) {
 const [month,setMonth]=useState(today().slice(0,7));const [day,setDay]=useState(today());
 const [meetings,setMeetings]=useState<Meeting[]>([]);const [selected,setSelected]=useState<Meeting|null>(null);
 const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [revision,setRevision]=useState(0);
 const scoped=useMemo(()=>projects.filter(p=>!projectId||p.id===projectId),[projects,projectId]);
 const writable=scoped.filter(p=>p.role!=='viewer');
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');setMeetings([]);
  Promise.all(scoped.map(async p=>{const rows:Meeting[]=[];let cursor:number|null=null;do{const data: {items:Meeting[];next_cursor:number|null}=await api('/projects/'+p.id+'/meetings?month='+month+(cursor?'&cursor='+cursor:''));rows.push(...data.items);cursor=data.next_cursor;}while(cursor);return rows;})).then(rows=>{if(!cancelled)setMeetings(rows.flat());}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};
 },[month,scoped,revision]);
 const first=new Date(month+'-01T12:00:00');const offset=(first.getDay()+6)%7;const total=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();
 const cells=Array.from({length:Math.ceil((offset+total)/7)*7},(_,i)=>{const d=new Date(first);d.setDate(1+i-offset);return localDate(d);});
 const dayMeetings=meetings.filter(m=>m.meeting_on===day);
 const dayTasks=tasks.filter(t=>(!projectId||t.project_id===projectId)&&t.planned_go_live_on===day);
 function navigateMonth(delta:number){const d=new Date(month+'-01T12:00:00');d.setMonth(d.getMonth()+delta);const value=localDate(d);setMonth(value.slice(0,7));setDay(value);}
 function create(){const p=writable[0];if(p)setSelected({id:0,project_id:p.id,title:'',meeting_on:day,participants:'',content:'',published:false,version:0,updated_at:''});}
 return <><div className="toolbar"><select aria-label="โปรเจกต์ในปฏิทิน" value={projectId??0} onChange={e=>onProject(Number(e.target.value))}><option value={0}>ทุกโปรเจกต์</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="secondary" aria-label="เดือนก่อน" onClick={()=>navigateMonth(-1)}>‹</button><strong className="month-label">{first.toLocaleDateString('th-TH',{month:'long',year:'numeric'})}</strong><button className="secondary" aria-label="เดือนถัดไป" onClick={()=>navigateMonth(1)}>›</button><button className="secondary" onClick={()=>{setMonth(today().slice(0,7));setDay(today());}}>วันนี้</button>{writable.length>0&&<button className="primary toolbar-end" onClick={create}>+ บันทึกประชุม</button>}</div>
 <div className="calendar-content">{error&&<div className="alert error" role="alert">{error}</div>}<div className="calendar-layout"><section className="calendar-panel" aria-label="ปฏิทินรายเดือน"><div className="calendar-weekdays">{['จ.','อ.','พ.','พฤ.','ศ.','ส.','อา.'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map(date=>{const ms=meetings.filter(m=>m.meeting_on===date);const ts=tasks.filter(t=>(!projectId||t.project_id===projectId)&&t.planned_go_live_on===date);return <button key={date} aria-label={dateLabel(date)+' ประชุม '+ms.length+' งาน '+ts.length} aria-pressed={day===date} className={'calendar-day '+(date.slice(0,7)!==month?'outside ':'')+(day===date?'selected ':'')+(date===today()?'today':'')} onClick={()=>{setDay(date);if(date.slice(0,7)!==month)setMonth(date.slice(0,7));}}><span className="day-number">{Number(date.slice(8))}</span>{ms.slice(0,2).map(m=><span className="calendar-event" key={m.id}>{m.title}</span>)}{ms.length>2&&<small>+{ms.length-2} ประชุม</small>}{ts.length>0&&<small className="calendar-deadline">◷ {ts.length} งานเริ่มใช้</small>}</button>})}</div><p className="calendar-legend">{loading?'กำลังโหลดรายงาน…':'ประชุมตามวันที่ · งานตามกำหนดเริ่มใช้งาน'}</p></section>
 <aside className="day-agenda"><header><small>บันทึกประจำวัน</small><h2>{dateLabel(day)}</h2></header><h3>รายงานประชุม <small>{dayMeetings.length}</small></h3>{dayMeetings.map(m=><button className="agenda-meeting" key={m.id} onClick={()=>setSelected(m)}><small>{projects.find(p=>p.id===m.project_id)?.name}</small><strong>{m.title}</strong><span>{m.published?'เผยแพร่ให้ผู้ชม':'เฉพาะทีม'} ↗</span></button>)}{!dayMeetings.length&&<p className="muted">{loading?'กำลังโหลด…':'ยังไม่มีรายงานประชุมในวันนี้'}</p>}{writable.length>0&&<button className="text-action" onClick={create}>+ เพิ่มรายงานวันนี้</button>}<h3>กำหนดเริ่มใช้งาน <small>{dayTasks.length}</small></h3>{dayTasks.map(t=><button className="report-task" key={t.id} onClick={()=>onTask(t)}><span>—</span><span>{t.title}<small>{projects.find(p=>p.id===t.project_id)?.name}</small></span></button>)}{!dayTasks.length&&<p className="muted">ไม่มีงานครบกำหนดวันนี้</p>}</aside></div></div>
 {selected&&<MeetingDrawer key={selected.id+'-'+selected.meeting_on} initial={selected} projects={projects} onClose={()=>setSelected(null)} onSaved={m=>{setSelected(m);setDay(m.meeting_on);setMonth(m.meeting_on.slice(0,7));setRevision(v=>v+1);}} onArchived={()=>{setSelected(null);setRevision(v=>v+1);}}/>}
 </>;
}
function MeetingDrawer({initial,projects,onClose,onSaved,onArchived}:{initial:Meeting;projects:Project[];onClose:()=>void;onSaved:(m:Meeting)=>void;onArchived:()=>void}) {
 const dialog=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.focus();return()=>previous?.focus();},[]);
 const [draft,setDraft]=useState(initial);const [tab,setTab]=useState<'edit'|'read'>(initial.id?'read':'edit');const [loading,setLoading]=useState(!!initial.id);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [archiveConfirm,setArchiveConfirm]=useState(false);
 const editable=projects.find(p=>p.id===draft.project_id)?.role!=='viewer';
 useEffect(()=>{let current=true;if(initial.id)api<Meeting>('/meetings/'+initial.id).then(m=>{if(current)setDraft(m);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[initial.id]);
 function field<K extends keyof Meeting>(key:K,value:Meeting[K]){setDraft(d=>({...d,[key]:value}));setSaved(false);}
 async function save(e?:React.FormEvent){e?.preventDefault();setBusy(true);setError('');try{const m=await api<Meeting>(draft.id?'/meetings/'+draft.id:'/projects/'+draft.project_id+'/meetings',{method:draft.id?'PATCH':'POST',body:JSON.stringify(draft)});setDraft(m);setSaved(true);setTab('read');onSaved(m);}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}
 async function reload(){setLoading(true);try{setDraft(await api<Meeting>('/meetings/'+draft.id));setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 return <div className="drawer-layer"><aside ref={dialog} tabIndex={-1} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex="0"]')??[]);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} className="drawer meeting-drawer" role="dialog" aria-modal="true" aria-label="รายงานประชุม"><header><div><small>{projects.find(p=>p.id===draft.project_id)?.name} / {dateLabel(draft.meeting_on)}</small><h1>{draft.title||'บันทึกประชุมใหม่'}</h1></div><button className="icon-button" aria-label="ปิดรายงานประชุม" onClick={onClose}>×</button></header><div className="drawer-tabs"><button className={tab==='read'?'active':''} onClick={()=>setTab('read')}>หน้าอ่าน</button>{editable&&<button className={tab==='edit'?'active':''} onClick={()=>setTab('edit')}>แก้ไข / วางสรุป AI</button>}</div>
 {loading?<div className="drawer-body">กำลังโหลด…</div>:<><div className="meeting-messages">{error&&<div className="alert error" role="alert">{error}{draft.id>0&&<button className="secondary" onClick={reload}>โหลดฉบับล่าสุด</button>}</div>}{saved&&<p className="good" role="status">บันทึกแล้ว</p>}</div>
 {tab==='read'?<div className="drawer-body meeting-paper"><div className="meeting-meta"><span>{draft.published?'เผยแพร่ให้ผู้ชม':'เฉพาะทีม'}</span><span>{dateLabel(draft.meeting_on)}</span></div>{draft.participants&&<p className="participants">ผู้เข้าร่วม: {draft.participants}</p>}{draft.content?<FormattedReport content={draft.content}/>:<p className="muted">วางสรุปการประชุมในแท็บแก้ไข แล้วดูรูปแบบได้ที่นี่</p>}<footer className="meeting-footnote">{draft.updated_at?'บันทึกล่าสุด '+new Date(draft.updated_at.replace(' ','T')+'Z').toLocaleString('th-TH'):'ยังไม่บันทึก'} · จัดรูปแบบจากข้อความที่ผู้เขียนส่งมา</footer>{editable&&<div className="drawer-actions"><button onClick={()=>setTab('edit')}>แก้ไขข้อความ</button><button className="primary" disabled={busy||!draft.title.trim()||!draft.content?.trim()||!draft.meeting_on} onClick={()=>save()}>{busy?'กำลังบันทึก…':'บันทึกรายงาน'}</button></div>}</div>:
 <form className="drawer-body meeting-editor" onSubmit={save}><div className="field-grid"><label className="field"><span>โปรเจกต์</span><select disabled={draft.id>0} value={draft.project_id} onChange={e=>field('project_id',Number(e.target.value))}>{projects.filter(p=>p.role!=='viewer').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>วันที่ประชุม</span><input type="date" required value={draft.meeting_on} onChange={e=>field('meeting_on',e.target.value)}/></label></div><label className="field"><span>หัวข้อการประชุม</span><input required value={draft.title} onChange={e=>field('title',e.target.value)} placeholder="เช่น ประชุมติดตามงานประจำวัน"/></label><label className="field"><span>ผู้เข้าร่วม (เฉพาะทีม)</span><input value={draft.participants??''} onChange={e=>field('participants',e.target.value)} placeholder="รายชื่อหรือทีมที่เข้าร่วม"/></label><div className="section-heading"><strong>สรุปการประชุมจาก AI หรือบันทึกของคุณ</strong>{!draft.content&&<button type="button" className="text-action" onClick={()=>field('content',template)}>ใช้โครงรายงาน</button>}</div><p className="muted">วางข้อความหรือ Markdown รองรับหัวข้อ รายการ เช็กลิสต์ และตาราง ดูผลในแท็บหน้าอ่านก่อนบันทึก</p><textarea aria-label="เนื้อหารายงานประชุม" required rows={16} value={draft.content??''} onChange={e=>field('content',e.target.value)} placeholder={'## ประเด็นที่หารือ\n- …\n\n## ข้อตกลง\n- …\n\n## งานที่ต้องติดตาม\n- ผู้รับผิดชอบ / กำหนดส่ง'}/><label className="publish-choice"><input type="checkbox" checked={draft.published} onChange={e=>field('published',e.target.checked)}/> ให้ผู้ชมที่มีสิทธิ์ในโปรเจกต์อ่านรายงานฉบับนี้ได้</label><div className="drawer-actions">{draft.id>0&&<button type="button" onClick={()=>setArchiveConfirm(true)}>เก็บเข้าคลัง</button>}<button type="button" onClick={()=>setTab('read')}>ดูรูปแบบ</button><button className="primary" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกรายงาน'}</button></div>{archiveConfirm&&<div className="archive-confirm"><p>เก็บรายงานนี้เข้าคลังและนำออกจากปฏิทิน?</p><button type="button" className="secondary" onClick={()=>setArchiveConfirm(false)}>กลับ</button><button type="button" className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/meetings/'+draft.id,{method:'DELETE',body:JSON.stringify({version:draft.version})});onArchived();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>ยืนยันเก็บเข้าคลัง</button></div>}</form>}</>}
 </aside></div>;
}
