import { useState } from 'react';
import type { Project, Task } from './types';
export function today() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Bangkok', year:'numeric',month:'2-digit',day:'2-digit' }).format(new Date()); }
export function dateLabel(value: string) { return new Date(value+'T12:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}); }
export function weekRange(value: string) { const d=new Date(value+'T12:00:00'); d.setDate(d.getDate()-((d.getDay()+6)%7)); const start=localDate(d);d.setDate(d.getDate()+6);return [start,localDate(d)]; }
export function localDate(d: Date) { return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }
const statuses=['รอทำ','กำลังทำ','รอทดสอบ','รอเปิดใช้','เปิดใช้งานแล้ว'];
export default function ProjectViews({ view, projects, tasks, projectId, onProject, onOpen }: {view:'overview'|'report';projects:Project[];tasks:Task[];projectId:number|null;onProject:(id:number,board?:boolean)=>void;onOpen:(t:Task)=>void}) {
 const [week,setWeek]=useState(today());const [start,end]=weekRange(week);
 const scoped=tasks.filter(t=>!projectId||t.project_id===projectId);
 const active=scoped.filter(t=>t.status!==4);const blockers=active.filter(t=>t.blocked_reason);
 const released=(t:Task)=>t.status===4&&!!t.actual_released_at&&t.actual_released_at.slice(0,10)>=start&&t.actual_released_at.slice(0,10)<=end;
 const delivered=scoped.filter(released);
 function download() {
  const lines=['# รายงานสัปดาห์',dateLabel(start)+' – '+dateLabel(end),''];
  for(const p of projects.filter(p=>!projectId||p.id===projectId)) {lines.push('## '+p.name);const pt=scoped.filter(t=>t.project_id===p.id);for(const group of [{label:'ส่งมอบแล้ว',items:pt.filter(released)},{label:'กำลังเดินหน้า',items:pt.filter(t=>t.status!==4&&!t.blocked_reason)},{label:'รอข้อสรุป',items:pt.filter(t=>t.status!==4&&t.blocked_reason)}]){if(group.items.length){lines.push('### '+group.label);for(const t of group.items)lines.push('- ['+statuses[t.status]+'] '+t.title+' · กำหนดเริ่มใช้ '+t.planned_go_live_on+(t.blocked_reason?' · '+t.blocked_reason:''));}}lines.push('');}
  const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='workboard-'+start+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 return <><div className="toolbar"><select aria-label="โปรเจกต์ในรายงาน" value={projectId??0} onChange={e=>onProject(Number(e.target.value))}><option value={0}>ทุกโปรเจกต์</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label="วันที่ในสัปดาห์" type="date" value={week} onChange={e=>e.target.value&&setWeek(e.target.value)}/><span className="period-label">{dateLabel(start)} – {dateLabel(end)}</span>{view==='report'&&<button className="secondary toolbar-end" onClick={download}>ดาวน์โหลดสรุป</button>}</div>
 <div className="view-content">
 {view==='overview'?<><div className="overview-metrics">{[[active.length,'งานที่ยังไม่จบ'],[active.filter(t=>t.status===1).length,'กำลังลงมือทำ'],[delivered.length,'เปิดใช้ในสัปดาห์นี้'],[blockers.length,'เรื่องที่ต้องช่วยตัดสินใจ']].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><div className="overview-layout"><section className="project-directory"><h2>โปรเจกต์ทั้งหมด</h2>{projects.filter(p=>!projectId||p.id===projectId).map(p=>{const pt=tasks.filter(t=>t.project_id===p.id);return <article key={p.id}><header><span className="project-avatar">{p.name.slice(0,2).toUpperCase()}</span><div><button onClick={()=>onProject(p.id,true)}>{p.name} ↗</button><p>{p.description}</p></div><small>เหลือ {pt.filter(t=>t.status!==4).length} งาน</small></header><p>{pt.find(t=>t.status===1)?.title??(pt.length?'ดูรายละเอียดในบอร์ดงาน':'ยังไม่มีงาน')}</p><footer>{statuses.map((s,i)=><span key={s}>{s} <b>{pt.filter(t=>t.status===i).length}</b></span>)}</footer></article>})}</section><aside className="overview-aside"><h2>ต้องการข้อสรุป</h2>{blockers.length?blockers.map(t=><button className="task-card" key={t.id} onClick={()=>onOpen(t)}><small>{projects.find(p=>p.id===t.project_id)?.name}</small><h2>{t.title}</h2><p className="blocked">{t.blocked_reason}</p></button>):<p className="muted">ไม่มีเรื่องติดขัดในข้อมูลที่คุณเข้าถึงได้</p>}</aside></div></>:
 <><p className="report-intro">สัปดาห์นี้เปิดใช้งาน <strong className="good">{delivered.length} งาน</strong> มีงานที่ยังดำเนินการ <strong>{active.length} งาน</strong> และต้องการข้อสรุป <strong className="accent">{blockers.length} เรื่อง</strong><small>ข้อมูลจากบอร์ดงาน · {dateLabel(start)} – {dateLabel(end)}</small></p>{projects.filter(p=>!projectId||p.id===projectId).map(p=>{const pt=scoped.filter(t=>t.project_id===p.id);const groups=[{label:'ส่งมอบแล้ว',items:pt.filter(released),tone:'good'},{label:'กำลังเดินหน้า',items:pt.filter(t=>t.status!==4&&!t.blocked_reason),tone:''},{label:'รอข้อสรุป',items:pt.filter(t=>t.status!==4&&t.blocked_reason),tone:'accent'}];return <section className="project-report" key={p.id}><div><button className="project-title" onClick={()=>onProject(p.id,true)}>{p.name} ↗</button><p>{p.description}</p></div><div>{groups.filter(g=>g.items.length).map(g=><section className="report-group" key={g.label}><h3 className={g.tone}>{g.label}</h3>{g.items.map(t=><button className="report-task" key={t.id} onClick={()=>onOpen(t)}><span>—</span><span>{t.title}{t.blocked_reason&&<small>{t.blocked_reason}</small>}</span></button>)}</section>)}{groups.every(g=>!g.items.length)&&<p className="muted">ไม่มีรายการในช่วงนี้</p>}</div></section>})}</>}
 </div></>;
}
